version: '3'
services:
  cassandra:
    container_name: cassandra
    image: cassandra
    ports:
      - "9042:9042"
  app:
    container_name: message
    image: message-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "cassandra"